44 fe admin add product popup
44mira/kitschy-co pull request #84
Opened 2024-11-22 08:54 UTC by sharmaigne

Missing features / to be refined once integration starts:
- show images when added
- drag and drop to move added images around (reorder) (non-priority)
- proper handling of error messages, right now it's just the zod default messages and it breaks the ui when it shows up

2024-11-23 06:42 UTC, ewandeyb approved these changes
LGTM

2024-11-23 18:09 UTC, 44mira requested changes
Requires some refactoring, but overall pretty good code.

2024-11-23 18:09 UTC, 44mira commented on frontend/src/lib/components/ui/input/input.svelte
> +		// 'border-input bg-background ring-offset-background placeholder:text-muted-foreground focus-visible:ring-ring flex h-10 w-full rounded-md border px-3 py-2 text-sm file:border-0 file:bg-transparen
Remove commented out code from commits. If you need anything from previous versions, you can checkout that commit.

2024-11-23 18:09 UTC, 44mira commented on frontend/src/routes/SignupDialog.svelte
> +				</Form.Field>
Is it possible to refactor `<Form.Field>` blocks into their own component?

2024-11-23 18:09 UTC, 44mira commented on frontend/src/routes/admin/AddProductsDialog.svelte
> +	function isCreatorIncluded(uuid: string) {
This function seems unnecessary, especially since you still call `creatorsValue.includes(uuid)` in line 52.

2024-11-23 18:09 UTC, 44mira commented on frontend/src/routes/admin/AddProductsDialog.svelte
> +	function toggleCreator(uuid: string) {
This function lacks documentation, at first glance I cannot tell what it is doing. what does toggling a Creator mean?

2024-11-23 18:09 UTC, 44mira commented on frontend/src/routes/admin/AddProductsDialog.svelte
> +			creatorsValue = creatorsValue.filter((c) => c !== uuid);
Consider doing the following:

```js
popped_creator = creatorsValue.indexOf(uuid);
creatorsValue.splice(popped_creator, 1);
```

This does the removal in-place, which seems to be the goal[^1] in this context.

[^1]: https://svelte.dev/docs/svelte/$state#Deep-state

2024-11-23 18:09 UTC, 44mira commented on frontend/src/routes/admin/AddProductsDialog.svelte
> +			creatorsValue = [...creatorsValue, uuid];
Refactor to use `push(uuid)`[^1] instead of iterating over creatorsValue.

[^1]: https://svelte.dev/docs/svelte/$state#Deep-state

2024-11-23 18:09 UTC, 44mira commented on frontend/src/routes/admin/AddProductsDialog.svelte
> +										console.log(isOpen);
Extraneous `console.log`

2024-11-23 22:17 UTC, sharmaigne commented on frontend/src/routes/SignupDialog.svelte
> +				</Form.Field>
you want each field to be a separate component?

2024-11-23 22:22 UTC, sharmaigne commented on frontend/src/lib/components/ui/input/input.svelte
> +		// 'border-input bg-background ring-offset-background placeholder:text-muted-foreground focus-visible:ring-ring flex h-10 w-full rounded-md border px-3 py-2 text-sm file:border-0 file:bg-transparen
noted

2024-11-24 08:51 UTC, 44mira commented on frontend/src/routes/SignupDialog.svelte
> +				</Form.Field>
I was suggesting to turn the repeating `Form.Field` blocks into a component, passing the differing parts as props.

2024-12-09 04:07 UTC, closed without merging